name: neo_banking
description: "A demo banking app made with Flutter to test device binding and WebuAuthn authentication with AIC or self hosted PingAM/IDM/DS."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  focus_detector: ^2.0.1
  google_fonts: ^7.0.0
  intl: ^0.20.2
  loader_overlay: ^5.0.0
  lottie: ^3.3.2
  nb_utils: ^7.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/logos/neobanklogo3.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/banking/
    - lib/assets/images/logos/
    - lib/assets/images/profile/
    - lib/assets/json/
    - lib/assets/lotties/
    - fonts/
